(function($) {
    $(document).ready(function() {
	
	$('#quincunx').scianimator({
	    'images': ['images/quincunx1.png', 'images/quincunx2.png', 'images/quincunx3.png', 'images/quincunx4.png', 'images/quincunx5.png', 'images/quincunx6.png', 'images/quincunx7.png', 'images/quincunx8.png', 'images/quincunx9.png', 'images/quincunx10.png', 'images/quincunx11.png', 'images/quincunx12.png', 'images/quincunx13.png', 'images/quincunx14.png', 'images/quincunx15.png', 'images/quincunx16.png', 'images/quincunx17.png', 'images/quincunx18.png', 'images/quincunx19.png', 'images/quincunx20.png', 'images/quincunx21.png', 'images/quincunx22.png', 'images/quincunx23.png', 'images/quincunx24.png', 'images/quincunx25.png', 'images/quincunx26.png', 'images/quincunx27.png', 'images/quincunx28.png', 'images/quincunx29.png', 'images/quincunx30.png', 'images/quincunx31.png', 'images/quincunx32.png', 'images/quincunx33.png', 'images/quincunx34.png', 'images/quincunx35.png', 'images/quincunx36.png', 'images/quincunx37.png', 'images/quincunx38.png', 'images/quincunx39.png', 'images/quincunx40.png', 'images/quincunx41.png', 'images/quincunx42.png', 'images/quincunx43.png', 'images/quincunx44.png', 'images/quincunx45.png', 'images/quincunx46.png', 'images/quincunx47.png', 'images/quincunx48.png', 'images/quincunx49.png', 'images/quincunx50.png', 'images/quincunx51.png', 'images/quincunx52.png', 'images/quincunx53.png', 'images/quincunx54.png', 'images/quincunx55.png', 'images/quincunx56.png', 'images/quincunx57.png', 'images/quincunx58.png', 'images/quincunx59.png', 'images/quincunx60.png', 'images/quincunx61.png', 'images/quincunx62.png', 'images/quincunx63.png', 'images/quincunx64.png', 'images/quincunx65.png', 'images/quincunx66.png', 'images/quincunx67.png', 'images/quincunx68.png', 'images/quincunx69.png', 'images/quincunx70.png', 'images/quincunx71.png', 'images/quincunx72.png', 'images/quincunx73.png', 'images/quincunx74.png', 'images/quincunx75.png', 'images/quincunx76.png', 'images/quincunx77.png', 'images/quincunx78.png', 'images/quincunx79.png', 'images/quincunx80.png', 'images/quincunx81.png', 'images/quincunx82.png', 'images/quincunx83.png', 'images/quincunx84.png', 'images/quincunx85.png', 'images/quincunx86.png', 'images/quincunx87.png', 'images/quincunx88.png', 'images/quincunx89.png', 'images/quincunx90.png', 'images/quincunx91.png', 'images/quincunx92.png', 'images/quincunx93.png', 'images/quincunx94.png', 'images/quincunx95.png', 'images/quincunx96.png', 'images/quincunx97.png', 'images/quincunx98.png', 'images/quincunx99.png', 'images/quincunx100.png', 'images/quincunx101.png', 'images/quincunx102.png', 'images/quincunx103.png', 'images/quincunx104.png', 'images/quincunx105.png', 'images/quincunx106.png', 'images/quincunx107.png', 'images/quincunx108.png', 'images/quincunx109.png', 'images/quincunx110.png', 'images/quincunx111.png', 'images/quincunx112.png'],
	    'width': 600,
	    'delay': 30,
	    'loopMode': 'loop',
 'controls': ['first', 'previous', 'play', 'next', 'last', 'loop', 'speed'], 'delayMin': 0
	});
	$('#quincunx').scianimator('play');
    });
})(jQuery);
